### ISSUE TITLE
ContactPicker fails to build

### ISSUE THREAD

**Issue by Waxhaw** [shrtlist/MeetingsSwiftUI#1]
MeetingsSwiftUI-main/Meetings/ContactPicker.swift:73:24: error build: Inheritance from non-protocol, non-class type 'ContactPicker.Coordinator' (aka 'any Coordinator')

MeetingsSwiftUI-main/Meetings/ContactPicker.swift:89:24: error build: Inheritance from non-protocol, non-class type 'ContactPicker.Coordinator' (aka 'any Coordinator')

**Comment by shrtlist** [comment]
Thanks @Waxhaw , investigating.

**Comment by shrtlist** [comment]
Fixed in PR https://github.com/shrtlist/MeetingsSwiftUI/pull/2
